_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: "tt_model_final.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("totaltext_train",)
  # TRAIN: ("totaltext_train","ain","icdar_2017_validation_mlt","icdar_2017_mlt","icdar_curvesynthtext_train1","icdar_curvesynthtext_train2",)
  TEST:  ("totaltext_test",)
SOLVER:
  STEPS: (360000,420000)
  MAX_ITER: 450000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"

# python projects/SWINTS/train_net.py --num-gpus 1 --config-file projects/SWINTS/configs/SWINTS-swin-finetune-totaltext.yaml